/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/useGLTF'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/particle_large-round.glb')
  return (
    <group ref={group} {...props}>
      <mesh
        material={materials['particle_large-round']}
        geometry={nodes['particle_large-round'].geometry}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
    </group>
  )
}

useGLTF.preload('/particle_large-round.glb')
