/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import * as THREE from 'three'
import React, {useRef, useState, useEffect} from 'react'
import {useFrame} from 'react-three-fiber'
import {useGLTF} from '@react-three/drei/useGLTF'

export default function ObjParticles(props) {
  const group = useRef()
  const {nodes, materials, animations} = useGLTF(
    '/models/juan/019/obj_particles_9.glb'
  )

  const actions = useRef()
  const [mixer] = useState(() => new THREE.AnimationMixer())
  useFrame((state, delta) => mixer.update(delta))
  useEffect(() => {
    console.log(group.current, 'group.current')
    console.log(
      props.xPos,
      props.yPos,
      props.zPos,
      props.xRot,
      props.yRot,
      props.zRot,
      props.scale
    )

    group.current.position.x = props.xPos
    group.current.position.y = props.yPos
    group.current.position.z = props.zPos

    group.current.rotation.x = props.xRot
    group.current.rotation.y = props.yRot
    group.current.rotation.z = props.zRot

    group.current.scale.z = props.xSca
    group.current.scale.y = props.ySca
    group.current.scale.z = props.zSca

    actions.current = {
      Anim_0: mixer.clipAction(animations[0], group.current),
    }
    return () => animations.forEach((clip) => mixer.uncacheClip(clip))
  }, [])
  return (
    <group ref={group} {...props}>
      <group rotation={[0, 4.8, 0]} scale={[0.04, 0.04, 0.04]}>
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane008.geometry}
          position={[6.54, -90.59, 128.13]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane009.geometry}
          position={[9.66, -127.13, 60.42]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane010.geometry}
          position={[139.89, -116.01, -53.85]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane011.geometry}
          position={[214.4, -32.81, -155.14]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane012.geometry}
          position={[209.8, 21.09, -222.41]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane013.geometry}
          position={[215.18, -41.91, 182.53]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane014.geometry}
          position={[205.76, -144.66, -193.42]}
          rotation={[0, 0, 1.66]}
        />
        <mesh
          material={materials['blue-particle']}
          geometry={nodes.Plane015.geometry}
          position={[214.12, 16.86, 33.69]}
          rotation={[0, 0, 1.66]}
        />
      </group>
    </group>
  )
}

// useGLTF.preload('/models/juan/018/obj_particles_8.glb')
