/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useLoader, useFrame, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { getMousePos, getMouseDegrees } from "./utils/getmouse";

const Bg3d = () => {
  const group = useRef()
  const { nodes, materials, animations } = useLoader(GLTFLoader, '/models/juan/particles/bg3d.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        material={materials['water-bg']}
        geometry={nodes['water-bg'].geometry}
        position={[0, 0, 497.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1136.83, -592.1, -639.47]}
      />
    </group>
  )
}

const ParticlesBits = () =>{
  return (
    
  )
}


const ParticlesScene = (props) => {
  const { gl } = useThree();
  const group = useRef();

  useEffect(() => {
    gl.gammaOutput = true;
    gl.gammaFactor = 2;
  }, []);

  useFrame((ani, delta) => {
    let degrees = getMouseDegrees(
      props.mouse.current.x,
      props.mouse.current.y,
      0.1
    );
    group.current.rotation.x = degrees.y;
    group.current.rotation.y = degrees.x + 3.1;
  });

  return (
    <group
      scale={[0.1, 0.1, 0.1]}
      position={[0, 0, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <ParticlesBits />
      <Bg3d />
    </group>
  );
}



export default ParticlesScene
