/*
auto-generated by: https://github.com/react-spring/gltfjsx
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useLoader, useFrame, useThree } from "react-three-fiber";
import { GLTFLoader } from "three/examples/jsm/loaders/GLTFLoader";
import { getMousePos, getMouseDegrees } from "./utils/getmouse";

export default function Particles(props) {
  const { gl } = useThree();
  const group = useRef();
  const bg = useRef();
  const ref = useRef();
  const { nodes, materials, animations } = useLoader(
    GLTFLoader,
    "/models/juan/particles/particles_007.glb"
  );

  useEffect(() => {
    materials["particle_large-round"].transparent = true;

    //  console.log(gl, 'gl')
    gl.gammaOutput = true;
    gl.gammaFactor = 2;

    //  materials['particle_large-round'].premultiplyAlpha = true
    //    console.log(materials['particle_large-round'].premultiplyAlpha, 'alphaMode')
    //    console.log(materials['particle_large-round'], 'material')
    materials["particle_large-round"].transparent = true;
    materials["particle_small-round"].transparent = true;
    materials["particle_blur-round"].transparent = true;
    materials["particle_large-round"].opacity = 0.2;
    materials["particle_small-round"].opacity = 0.2;
    materials["particle_blur-round"].opacity = 0.2;
    materials["particle_large-round"].depthWrite = false;
    materials["particle_small-round"].depthWrite = false;
    materials["particle_blur-round"].depthWrite = false;
    //  materials['water-bg'].visible = true
    //  materials['water-bg'].flatShading = true
    //  materials['water-bg'].emissive = {r: 255, g: 255, b: 255}
    //  materials['water-bg'].emissiveIntensity = 0.0001
    //materials['water-bg'].clipShadows = true

    //  materials['water-bg'].reflectivity = 0
    //materials['particle_large-round'].alphaTest = .4
    // materials['particle_small-round'].alphaTest = .4
    // materials['water-bg'].alphaTest = .4
  }, []);

  useFrame((ani, delta) => {
    let degrees = getMouseDegrees(
      props.mouse.current.x,
      props.mouse.current.y,
      0.1
    );
    group.current.rotation.x = degrees.y;
    group.current.rotation.y = degrees.x + 3.1;
  });

  return (
    <group
      scale={[0.1, 0.1, 0.1]}
      position={[0, 0, 0]}
      ref={group}
      {...props}
      dispose={null}
    >
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round"].geometry}
        position={[235.79, 4.11, 35.3]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round001"].geometry}
        position={[-260.41, -65.7, -50.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round002"].geometry}
        position={[-271.61, 22.73, 360.88]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round003"].geometry}
        position={[63.98, 71.7, 406.35]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round004"].geometry}
        position={[42.82, -162.19, 92.72]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round005"].geometry}
        position={[110.96, -171.99, 421.8]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round006"].geometry}
        position={[140.2, -118.42, 485.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round007"].geometry}
        position={[275.63, -196.73, 110.97]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round008"].geometry}
        position={[357.78, 143.29, 232.82]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round009"].geometry}
        position={[293.32, -97.57, 285.87]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_large-round"]}
        geometry={nodes["particle_large-round010"].geometry}
        position={[-202.22, 24.55, 155.52]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round"].geometry}
        position={[-183.32, 43.29, 264.05]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round001"].geometry}
        position={[-451.48, 24.79, 219.77]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round002"].geometry}
        position={[-289.7, 170.91, 176.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round003"].geometry}
        position={[33.43, 99.8, 316.82]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round004"].geometry}
        position={[125.13, 41.94, 77.72]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round005"].geometry}
        position={[-293.54, 226.84, 217.25]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round006"].geometry}
        position={[-481.62, 265.58, 227.77]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round007"].geometry}
        position={[-379.08, 251.38, 482.33]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round008"].geometry}
        position={[81.09, -87.79, 415.94]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round009"].geometry}
        position={[51.36, 8.4, 230.48]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round010"].geometry}
        position={[-184.72, 107.67, 87.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round011"].geometry}
        position={[-227.93, 18.86, 208.21]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round012"].geometry}
        position={[-225.32, 213.92, 384.54]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round013"].geometry}
        position={[-104.68, 55.44, 98.74]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round014"].geometry}
        position={[-325.43, 199.74, 113.25]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round015"].geometry}
        position={[-298.29, 59.86, 118.77]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round016"].geometry}
        position={[38.89, 171.8, 221.89]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round017"].geometry}
        position={[75.48, 183.84, 444.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round018"].geometry}
        position={[73.56, 106.59, 421.49]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round019"].geometry}
        position={[-262.48, 159.05, 335.34]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round020"].geometry}
        position={[308.8, 112.25, 427.19]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round021"].geometry}
        position={[166.77, 192.22, 392.21]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round022"].geometry}
        position={[-238.42, 120.38, 429.5]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round023"].geometry}
        position={[244.44, 83.92, 443.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round024"].geometry}
        position={[52.61, 202.79, 412.44]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round025"].geometry}
        position={[-368.56, 62.13, 329.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round026"].geometry}
        position={[290.46, 280.58, 429.45]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round027"].geometry}
        position={[102.05, 123.98, 200.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round028"].geometry}
        position={[228.02, -72.54, 219.33]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round029"].geometry}
        position={[126.66, -193.15, 377.98]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round030"].geometry}
        position={[198.99, 139.06, 224.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round031"].geometry}
        position={[-343.11, -26.17, 55.87]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round032"].geometry}
        position={[-239.82, -77.39, 296.51]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round033"].geometry}
        position={[-71.21, -88.28, 332]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round034"].geometry}
        position={[129.48, 46.42, 431.51]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round035"].geometry}
        position={[94.45, 23.43, 388.2]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round036"].geometry}
        position={[-63.31, 281.15, 418.55]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round037"].geometry}
        position={[121.13, 293.01, 353.7]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round038"].geometry}
        position={[342.62, 66.82, 445.61]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round039"].geometry}
        position={[-68.1, -167.44, 329.69]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round040"].geometry}
        position={[-50.48, -120.91, 63.3]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round041"].geometry}
        position={[-296.02, -197.9, 343.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round042"].geometry}
        position={[-347.46, -3.62, 256.97]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round043"].geometry}
        position={[-259.87, -17.95, 311.81]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round044"].geometry}
        position={[-141.33, 5.48, 93.41]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round045"].geometry}
        position={[-111.39, -16.7, 405.91]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round046"].geometry}
        position={[-222.61, -102.38, 431.91]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round047"].geometry}
        position={[-46.81, -34.55, 391.47]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round048"].geometry}
        position={[5.74, -161.51, 441.92]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round049"].geometry}
        position={[275.5, -190.75, 432.63]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round050"].geometry}
        position={[381.09, -92.54, 148.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round051"].geometry}
        position={[248.07, -10.12, 126.94]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round052"].geometry}
        position={[92.45, -3.73, 143.81]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round053"].geometry}
        position={[71.23, -63.73, 264.84]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round054"].geometry}
        position={[-395.41, 108.32, 412.69]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round055"].geometry}
        position={[529.76, 247.02, 461.12]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round056"].geometry}
        position={[563.25, 21.9, 241.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round057"].geometry}
        position={[477.35, 210.77, 243.23]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round058"].geometry}
        position={[377.7, 284.74, 297.71]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round059"].geometry}
        position={[501.65, -7.35, 340.49]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round060"].geometry}
        position={[533.72, -175.77, 290.5]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round061"].geometry}
        position={[320.39, -276.96, 340.92]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round062"].geometry}
        position={[157.18, -266.74, 337.81]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round063"].geometry}
        position={[33.72, -220.19, 71.04]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round064"].geometry}
        position={[-135.6, -148.83, 234.4]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round065"].geometry}
        position={[-210.99, -135.29, 166.46]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round066"].geometry}
        position={[-132.46, -207.67, 285.25]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round067"].geometry}
        position={[-400.46, -277.35, 549.75]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round068"].geometry}
        position={[-530.47, -126.41, 202.74]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round069"].geometry}
        position={[-459.02, -171.07, 297.88]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round070"].geometry}
        position={[-353.11, -262.8, 427.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round071"].geometry}
        position={[-358.4, -336.57, 355.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round072"].geometry}
        position={[-269.67, -340.26, 243.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round073"].geometry}
        position={[-153.08, -334.64, 285.95]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round074"].geometry}
        position={[-117.08, -279.25, 464.38]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round075"].geometry}
        position={[56.49, -420.23, 385.39]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round076"].geometry}
        position={[461.05, -452.93, 405.73]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round077"].geometry}
        position={[459.34, -217.89, 237.89]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round078"].geometry}
        position={[-233.71, 339.95, 239.27]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round079"].geometry}
        position={[257.65, 99.46, 268.36]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round080"].geometry}
        position={[178.13, 77.04, 243.03]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round081"].geometry}
        position={[-125.57, 103.31, 307.57]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round082"].geometry}
        position={[-145.88, -47.44, 255.69]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round083"].geometry}
        position={[347.35, 187.46, 445.07]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round084"].geometry}
        position={[-388.69, -153.26, 231.33]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round085"].geometry}
        position={[-388.38, -69.99, 200.21]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round086"].geometry}
        position={[-459.87, -183.55, 161.86]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round087"].geometry}
        position={[268.11, 287.18, 127.34]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round088"].geometry}
        position={[290.41, 229.17, 195.67]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round089"].geometry}
        position={[391.88, 134.73, 181.36]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_small-round"]}
        geometry={nodes["particle_small-round090"].geometry}
        position={[-338.27, 227.24, 142.91]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[8.9, 8.9, 8.9]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round"].geometry}
        position={[380.74, 8.77, 400.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round001"].geometry}
        position={[161.38, -44.62, 257.46]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round002"].geometry}
        position={[-4.02, 39.92, 303.09]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round003"].geometry}
        position={[-176.24, -125.19, 206.6]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round004"].geometry}
        position={[-32.01, -81.9, 22.47]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round005"].geometry}
        position={[-152.03, 109.29, 273.7]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round006"].geometry}
        position={[125.62, 150.63, 384.44]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round007"].geometry}
        position={[-105.63, 205.53, 428.02]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round008"].geometry}
        position={[-23.26, 156.08, 456.1]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round009"].geometry}
        position={[173.49, -219.93, 377.22]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round010"].geometry}
        position={[18.06, -177.18, 172.65]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round011"].geometry}
        position={[296.58, 266.79, 324.9]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["particle_blur-round"]}
        geometry={nodes["particle_blur-round012"].geometry}
        position={[386.54, -133.28, 350.94]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[19.53, 19.53, 19.53]}
      />
      <mesh
        material={materials["water-bg"]}
        geometry={nodes["water-bg"].geometry}
        position={[0, 0, 497.26]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={[-1136.83, -592.1, -639.47]}
      />
    </group>
  );
}
